DROP TABLE IF EXISTS "comments";
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "items" CASCADE;
DROP TABLE IF EXISTS "requests";
DROP TABLE IF EXISTS "bookings"; --Оставлено, чтобы пройти тесты. Закомментировать для работы--

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(64)                             NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           bigint    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description  varchar   NOT NULL,
    requestor_id bigint    NOT NULL,
    created      timestamp NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_requestor FOREIGN KEY (requestor_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    is_available BOOLEAN                                 NOT NULL,
    owner_id     BIGINT                                  NOT NULL,
    request_id   BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_request FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    id        bigint    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    meaning   varchar   NOT NULL,
    item_id   BIGINT    NOT NULL,
    author_id bigint    NOT NULL,
    created   timestamp NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         bigint    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    start_date timestamp NOT NULL,
    end_date   timestamp NOT NULL,
    item_id    bigint    NOT NULL,
    booker_id  bigint    NOT NULL,
    status     varchar   NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT fk_bookings_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT pk_booker FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
)


